import Head from "next/head";
import Image from "next/image";
import Navbar from "components/Navbar";
import PictSection from "../../components/pictSection";
import Review from "components/Review";
import HeroNew from "components/HeroNew";
import Gallery from "./keyboard/gallery";
export default function Home() {
  return (
    <>
      <Head>
        <title>Adrian Karuna Soetikno</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,400;0,500;0,700;1,600&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>
        {/* <Hero/> */}
        <HeroNew
          heading="find your perfect keyboard"
          message="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, enim eu aliquet suscipit, lacus magna pulvinar massa, vel lacinia tellus purus eu nisi. Nullam vel purus ac odio interdum viverra. Nam ullamcorper neque at ante tincidunt, a vestibulum odio malesuada."
        />
        <PictSection />
        <Gallery/>
        <Review />

        

      </main>
    </>
  );
}
